### PR TITLE
Migrate from setuptools/distutils to meson

### PR DESCRIPTION
**Pull request by eylles**
initial work to fully migrate towards meson, huge thanks to karna for not just sending the patch but testing that it builds under debian testing.

as outlined on the patch comment there is still work to do.

### CODE REVIEW

**Comment by eylles** [comment]
yes this is a work towards #9 #13 #14

i guess @ionenwks @pirate486743186 and @eli-schwartz will be happy to know this is finally getting worked on.

**Comment by eli-schwartz** [comment]
Nice. The meson.build part looks mostly like the one minimally tested and suggested at https://github.com/ueber-devel/ueberzug/issues/14#issuecomment-1636968170 but the summary() usage is new.

IIRC meson already prints settings that were changed from the defaults, although py_install_dir isn't a setting to change so still possibly good to see. I'm not sure whether the other settings (get_option usages) even matter for ueberzug's use case? In theory you could just elide printing those. :)

**Comment by eylles** [comment]
@eli-schwartz 
>I'm not sure whether the other settings (get_option usages) even matter for ueberzug's use case?

i thought so at first, but since the long term intention is to try and have some feature parity with U++ they could come in handy in the future.

also there is another rather pressing problem, which is that the distribution name `ueberzug` is blocked on pypi #20 so it is not possible to upload a new `ueberzug` there and the PEP 541 request doesn't seem like it will have a quick resolution, so either as a project we give up on pypi or upload under a different name, of ever suggestion i like `ueberzug-community` the most, but that causes a "small" issue with the name of the wheel changing since twine infers the pypi dist name from the wheel, so that would create a burden either with the distro maintainers to change the name on the pyproject.toml with a patch OR that the gh action to build and upload the pypi dist will need to change the name var... and neither seems "correct" if you ask me.

**Comment by eylles** [comment]
> 
> also there is another rather pressing problem, which is that the distribution name `ueberzug` is blocked on pypi #20 so it is not possible to upload a new `ueberzug` there and the PEP 541 request doesn't seem like it will have a quick resolution, so either as a project we give up on pypi or upload under a different name, of ever suggestion i like `ueberzug-community` the most, but that causes a "small" issue with the name of the wheel changing since twine infers the pypi dist name from the wheel, so that would create a burden either with the distro maintainers to change the name on the pyproject.toml with a patch OR that the gh action to build and upload the pypi dist will need to change the name var... and neither seems "correct" if you ask me.

will figure this one later, will test some stuff and hopefully merge this today.

**Comment by eylles** [comment]
> 
> will test some stuff and hopefully merge this today.

> hopefully merge this today.

> merge this today.

lol, lmao even.

**Comment by eli-schwartz** [comment]
You don't get a high score until you've delayed merging your own PR by a couple of years. :P 

(Been there, done that, hid the t-shirt in the back of the drawer.)

**Pull request merged**
